apiVersion: v1
kind: Service
metadata:
  name: infra-101-best-ever-service
spec:
  selector:
    app: scratch
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
